### Welcome to Hexo-Theme-Lx
###Author:blleng(https://github.com/blleng)
###Version:v0.4.4
version: 0.4.4

# favicon
favicon: favicon.ico

# Theme-color for Android Chrome
theme_color: "#131424"

# personal information
personal_des: "<a href='https://en.wikipedia.org/wiki/Numeronym'>Numeronym</a> for salomonvalverde"

# avatar
avatar: /images/s13e-avatar-blkwh.jpg

###The options below are images information
# Home cover
cover: /images/wh-3zkgwy.png
# page cover
postcover: /images/wh-zy5d8o.jpg
# the cover of newer or older post
pre_post: /images/wh-y8jx3x.png
nex_post: /images/wh-13dvvv.jpg

# menu content
menu:
  category: false #category
  pages: #the page created by yourself
    enable: true
    links:
      About: about/
      Uses: uses/
  friends:
    enable: false

# social links
#
social:
  enable: true
  links:
    GitHub:
      icon: github-alt
      link: https://github.com/salverde
    Gitlab:
      icon: gitlab
      link: https://gitlab.com/salverde
    Email:
      icon: send
      link: mailto:s13e.xl@icloud.com
    Instagram:
      icon: instagram
      link: https://instagram.com/salverde

# local search
#install first:
#'npm install hexo-generator-searchdb -s'
local_search:
  enable: false
  trigger: auto #'auto' or 'manual'
  top_n_per_article: 1
  unescape: false
  preload: false
  placeholder: Search...

# footer
footer:

# Analytics
google_analytics: #Google ID
baidu_analytics: #Baidu ID

# Lx use valine as comment system
# You should create an application in Leancloud to get the appid and appkey
comment:
  enable: true
  appid: 0ucyNhrywwPZE9yBGPBiIZOJ-MdYXbMMI
  appkey: zdFTwXMg6mvM7Hs2SfRA4IXw
  notify: true
  verify: false
  placeholder: Say something.
  avatar: identicon
  guest_info: nick,mail,link
  pageSize: 10
  language: en
  cdn: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

# Mathjax
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js

# FontAwesome-CDN
font_awesome: https://cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css

# Font
font:
  enable: true
  host: https://fonts.googleapis.com
  codes: ##the font for codes
    enable: true
    family: Fira Mono
  else: ##the font for rest site
    enable: true
    family: Encode Sans Condensed

# Custom head code ex: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script>
# custom_head:

# Custom CSS
# If true, Lx will load 'source/css/custom.styl'
custom_css: true

########### Develop Options ############
############# Warning ##################
####### Don't edit options below #######
## unless you know what you are doing ##
############# Warning ##################

#The dir of Js and Css
base_file:
  jquery_cdn: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js
  js: https://cdn.jsdelivr.net/npm/theme-lx@0.4.4/source/dist/js/
  css: https://cdn.jsdelivr.net/npm/theme-lx@0.4.4/source/dist/css/main.min.css
