# See explaination in
# Blog config
keywords: s13e blog computer linux software developer
author: s13e
description: Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
defaultTheme: default # light or dark or default

theme: lx

title: s13e.lx
